# Raw to Silver: Data Preprocessing
This notebook demonstrates how to preprocess transaction data from the raw layer and save a cleaned version to the silver layer. You can adapt this workflow for other raw datasets in your project.

In [7]:


import pandas as pd

RAW_PATH = "../raw-data/transactions10K.csv"
SILVER_PATH = "../Silver-data/transactions_clean.csv"

# Load raw transactions data
transactions = pd.read_csv(RAW_PATH)
print("Raw Transactions Shape:", transactions.shape)
transactions.head()

Raw Transactions Shape: (9458, 19)

,transaction_id,user_id,product_id,shop_id,quantity,unit_price,total_amount,discount_percent,discount_amount,tax_percent,tax_amount,final_amount,payment_method,transaction_status,transaction_date,transaction_ts,delivery_date,delivery_address,notes
0,1,428.0,1671.0,4.0,2,2500.0,5000.0,10,500.0,8,360.0,4860.0,Debit Card,Completed,2024-03-28,2024-03-28 15:07:06.244063,2024-04-02 15:07:06.244063,"73969 Sonia Greens, Taylorborough, NV 75757",Order for Edgy Wide Leg Polos
1,2,209.0,387.0,3.0,2,2500.0,5000.0,0,0.0,8,400.0,5400.0,Credit Card,Completed,2024-07-24,2024-07-24 15:50:58.253247,2024-07-26 15:50:58.253247,"8443 Conner Union Suite 772, Kellystad, NM 85205",Order for Retro Smart Tanks
2,3,488.0,1038.0,6.0,3,8000.0,24000.0,0,0.0,8,1920.0,25920.0,Digital Wallet,Completed,2024-09-30,2024-09-30 10:07:37.551146,2024-10-05 10:07:37.551146,"Unit 7811 Box 6718, DPO AA 90446",Order for Heritage Retro Kimono
3,4,196.0,1038.0,6.0,3,8000.0,24000.0,0,0.0,8,1920.0,25920.0,Digital Wallet,Completed,2022-09-26,2022-09-26 12:28:53.521022,2022-10-03 12:28:53.521022,"00320 Michael Crescent, Hardychester, VA 43123",Order for Heritage Retro Kimono
4,5,226.0,1548.0,22.0,2,NaN,NaN,0,NaN,8,NaN,NaN,Bank Transfer,Completed,2023-10-28,2023-10-28 07:43:14.139814,2023-10-30 07:43:14.139814,"830 Shawn Center Apt. 903, Chaneyfurt, OK 16545",Order for Bright Lightweight Coats

## Step 1: Remove Duplicates

In [8]:
# Remove duplicate rows
transactions = transactions.drop_duplicates()
print("After removing duplicates:", transactions.shape)

After removing duplicates: (9458, 19)

## Step 2: Handle Missing Values

In [9]:
# Check for missing values
missing_summary = transactions.isnull().sum()
print("Missing values per column:\n", missing_summary)

Missing values per column:
 transaction_id          0
user_id                 0
product_id              0
shop_id               296
quantity                0
unit_price            266
total_amount          266
discount_percent        0
discount_amount       266
tax_percent             0
tax_amount            266
final_amount          266
payment_method          0
transaction_status      0
transaction_date       13
transaction_ts         13
delivery_date         666
delivery_address      290
notes                   0
dtype: int64

In [ ]:
# ---------------------------
# Drop rows with critical nulls
# ---------------------------
critical_cols = [
    'shop_id',
    'unit_price',
    'total_amount',
    'discount_amount',
    'tax_amount',
    'final_amount',
    'transaction_date',
    'transaction_ts',
    'delivery_address',
    'delivery_date'
]

transactions = transactions.dropna(subset=critical_cols)

missing_summary = transactions.isnull().sum()
print("Missing values per column:\n", missing_summary)

print("After Cleaned missings:", transactions.shape)

Missing values per column:
 transaction_id        0
user_id               0
product_id            0
shop_id               0
quantity              0
unit_price            0
total_amount          0
discount_percent      0
discount_amount       0
tax_percent           0
tax_amount            0
final_amount          0
payment_method        0
transaction_status    0
transaction_date      0
transaction_ts        0
delivery_date         0
delivery_address      0
notes                 0
dtype: int64
After Cleaned missings: (8008, 19)

In [13]:
transactions.head()

,transaction_id,user_id,product_id,shop_id,quantity,unit_price,total_amount,discount_percent,discount_amount,tax_percent,tax_amount,final_amount,payment_method,transaction_status,transaction_date,transaction_ts,delivery_date,delivery_address,notes
0,1,428.0,1671.0,4.0,2,2500.0,5000.0,10,500.0,8,360.0,4860.0,Debit Card,Completed,2024-03-28,2024-03-28 15:07:06.244063,2024-04-02 15:07:06.244063,"73969 Sonia Greens, Taylorborough, NV 75757",Order for Edgy Wide Leg Polos
1,2,209.0,387.0,3.0,2,2500.0,5000.0,0,0.0,8,400.0,5400.0,Credit Card,Completed,2024-07-24,2024-07-24 15:50:58.253247,2024-07-26 15:50:58.253247,"8443 Conner Union Suite 772, Kellystad, NM 85205",Order for Retro Smart Tanks
2,3,488.0,1038.0,6.0,3,8000.0,24000.0,0,0.0,8,1920.0,25920.0,Digital Wallet,Completed,2024-09-30,2024-09-30 10:07:37.551146,2024-10-05 10:07:37.551146,"Unit 7811 Box 6718, DPO AA 90446",Order for Heritage Retro Kimono
3,4,196.0,1038.0,6.0,3,8000.0,24000.0,0,0.0,8,1920.0,25920.0,Digital Wallet,Completed,2022-09-26,2022-09-26 12:28:53.521022,2022-10-03 12:28:53.521022,"00320 Michael Crescent, Hardychester, VA 43123",Order for Heritage Retro Kimono
5,6,189.0,964.0,12.0,2,8000.0,16000.0,0,0.0,8,1280.0,17280.0,COD,Completed,2023-10-03,2023-10-03 11:58:59.330475,2023-10-06 11:58:59.330475,"8073 Alex Common Suite 225, Lake Tammy, CT 90169",Order for Soft Tailored Hoodies & Jackets

## Step 3: Data Type Corrections (if needed)

In [12]:
# Example: Convert date columns to datetime
if 'transaction_date' in transactions.columns:
    transactions['transaction_date'] = pd.to_datetime(transactions['transaction_date'], errors='coerce')

## Step 4: Save Cleaned Data to Silver Layer

In [14]:
# Save the cleaned dataframe to the silver layer
import os
os.makedirs(os.path.dirname(SILVER_PATH), exist_ok=True)
transactions.to_csv(SILVER_PATH, index=False)
print(f"Cleaned transactions data saved to {SILVER_PATH}")

Cleaned transactions data saved to ../Silver-data/transactions_clean.csv

---

Repeat this process for each raw dataset (users, products, shops, etc.) by changing the input/output paths and adapting the cleaning steps as needed.