# Raw to Silver: Data Preprocessing
This notebook demonstrates how to preprocess transaction data from the raw layer and save a cleaned version to the silver layer. You can adapt this workflow for other raw datasets in your project.

In [2]:


import pandas as pd

RAW_PATH = "../raw-data/user_preferences_dataset.csv"
SILVER_PATH = "../Silver-data/users_preferences_clean.csv"

# Load raw users data
usersPreferences = pd.read_csv(RAW_PATH)
print("Raw Users Shape:", usersPreferences.shape)
usersPreferences.head()

Raw Users Shape: (525, 11)

,preference_id,user_id,preferred_categories,preferred_colors,preferred_fabrics,preferred_brands,preferred_styles,skin_tone,body_type,price_sensitivity,updated_ts
0,1.0,1.0,"UTILITY PANTS, CHINOS, OVERSIZE TEE","Brown, Off-white, Teal","Modal, Cotton",Brand_3,"Casual, Athleisure, Formal",Medium Skin,Tall Friendly,Medium,2025-11-19 14:56:19.269218
1,2.0,2.0,"JOGGERS & PANTS, BLAZERS, SHORTS","Polka Dot, Teal, Tan","Linen, Denim",Brand_6,"Athleisure, Formal, Beach Wear",Medium Skin,Curvy Friendly,Medium,2025-11-19 14:56:19.269398
2,3.0,3.0,"COATS, JOGGERS & PANTS, SWEATSHIRTS","Brown, Tan, Yellow","Denim, Modal",Brand_19,"Hipster, Beach Wear, Eco-friendly",Dark Skin,Curvy Friendly,Medium,2025-11-19 14:56:19.269539
3,4.0,4.0,"BEACH WEAR, COATS, UTILITY PANTS","Red, Striped, Peach","Linen, Fleece",Brand_8,"Hipster, Luxury, Y2K",Fair Skin,Skinny Friendly,Medium,2025-11-19 14:56:19.269663
4,5.0,5.0,"SHORTS, OVERSIZE TEE, UTILITY PANTS","Tie-dye, Orange, Charcoal","Bamboo, Tencel",Brand_1,NaN,Dark Skin,Curvy Friendly,High,2025-11-19 14:56:19.269789

## Step 1: Remove Duplicates

In [11]:
# Remove duplicate rows
usersPreferences = usersPreferences.drop_duplicates()
print("After removing duplicates:", usersPreferences.shape)

After removing duplicates: (471, 11)

## Step 2: Handle Missing Values

In [9]:
# Check for missing values
missing_summary = usersPreferences.isnull().sum()
print("Missing values per column:\n", missing_summary)

Missing values per column:
 preference_id           0
user_id                 0
preferred_categories    0
preferred_colors        0
preferred_fabrics       0
preferred_brands        0
preferred_styles        0
skin_tone               0
body_type               0
price_sensitivity       0
updated_ts              0
dtype: int64

In [8]:
# Drop rows where t_id is missing
usersPreferences = usersPreferences.dropna(subset=['preference_id'])
usersPreferences = usersPreferences.dropna(subset=['user_id'])
# Fill missing columns
usersPreferences['preferred_categories'] = usersPreferences['preferred_categories'].fillna(usersPreferences['preferred_categories'].mode()[0])
usersPreferences['preferred_colors'] = usersPreferences['preferred_colors'].fillna(usersPreferences['preferred_colors'].mode()[0])
usersPreferences['preferred_fabrics'] = usersPreferences['preferred_fabrics'].fillna(usersPreferences['preferred_fabrics'].mode()[0])
usersPreferences['preferred_brands'] = usersPreferences['preferred_brands'].fillna(usersPreferences['preferred_brands'].mode()[0])
usersPreferences['preferred_styles'] = usersPreferences['preferred_styles'].fillna(usersPreferences['preferred_styles'].mode()[0])
usersPreferences['skin_tone'] = usersPreferences['skin_tone'].fillna(usersPreferences['skin_tone'].mode()[0])
usersPreferences['body_type'] = usersPreferences['body_type'].fillna(usersPreferences['body_type'].mode()[0])
usersPreferences['price_sensitivity'] = usersPreferences['price_sensitivity'].fillna(usersPreferences['price_sensitivity'].mode()[0])

usersPreferences['updated_ts'] = usersPreferences['updated_ts'].fillna(pd.Timestamp.now())

In [10]:
usersPreferences.head()

,preference_id,user_id,preferred_categories,preferred_colors,preferred_fabrics,preferred_brands,preferred_styles,skin_tone,body_type,price_sensitivity,updated_ts
0,1.0,1.0,"UTILITY PANTS, CHINOS, OVERSIZE TEE","Brown, Off-white, Teal","Modal, Cotton",Brand_3,"Casual, Athleisure, Formal",Medium Skin,Tall Friendly,Medium,2025-11-19 14:56:19.269218
1,2.0,2.0,"JOGGERS & PANTS, BLAZERS, SHORTS","Polka Dot, Teal, Tan","Linen, Denim",Brand_6,"Athleisure, Formal, Beach Wear",Medium Skin,Curvy Friendly,Medium,2025-11-19 14:56:19.269398
2,3.0,3.0,"COATS, JOGGERS & PANTS, SWEATSHIRTS","Brown, Tan, Yellow","Denim, Modal",Brand_19,"Hipster, Beach Wear, Eco-friendly",Dark Skin,Curvy Friendly,Medium,2025-11-19 14:56:19.269539
3,4.0,4.0,"BEACH WEAR, COATS, UTILITY PANTS","Red, Striped, Peach","Linen, Fleece",Brand_8,"Hipster, Luxury, Y2K",Fair Skin,Skinny Friendly,Medium,2025-11-19 14:56:19.269663
4,5.0,5.0,"SHORTS, OVERSIZE TEE, UTILITY PANTS","Tie-dye, Orange, Charcoal","Bamboo, Tencel",Brand_1,"Luxury, Casual, Preppy",Dark Skin,Curvy Friendly,High,2025-11-19 14:56:19.269789

## Step 3: Data Type Corrections (if needed)

In [12]:
usersPreferences.dtypes

preference_id           float64
user_id                 float64
preferred_categories     object
preferred_colors         object
preferred_fabrics        object
preferred_brands         object
preferred_styles         object
skin_tone                object
body_type                object
price_sensitivity        object
updated_ts               object
dtype: object

In [13]:
usersPreferences['preference_id'] = usersPreferences['preference_id'].astype(int)
usersPreferences['user_id'] = usersPreferences['user_id'].astype(int)

## Step 4: Save Cleaned Data to Silver Layer

In [14]:
# Save the cleaned dataframe to the silver layer
import os
os.makedirs(os.path.dirname(SILVER_PATH), exist_ok=True)
usersPreferences.to_csv(SILVER_PATH, index=False)
print(f"Cleaned user preferences data saved to {SILVER_PATH}")

Cleaned user preferences data saved to ../Silver-data/users_preferences_clean.csv

---

Repeat this process for each raw dataset (users, products, shops, etc.) by changing the input/output paths and adapting the cleaning steps as needed.